
apiVersion: v1
kind: Service
metadata:
  labels:
    name: glasswall-crawler
  name: glasswall-crawler-service
spec:
  ports:
    - port: 5002
      targetPort: 5002
      protocol: TCP
  selector:
    app: glasswall-crawler

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: glasswall-crawler-configmap
data:
  SCRAPY_PROJECT_ID: malicious_file_crawler
  SCRAPE_SITES: VIRUSSHARE,DASMAL,TEKDEF,ZOO,MALSHARE
  MINIO_URL: Please enter minio url
  MINIO_ACCESS_KEY: Please enter minio access key
  MINIO_SECRET_KEY: Please enter minio secret key
  MALSHARE_API_KEY: Please enter malshare api key
  VIRUSSHARE_API_KEY: Please enter virushshare api key
  storage_adapter_url: http://storage-adapter-service:5002/
  SCRAPY_PROJECT_ID: malicious_file_crawler
  SCRAPE_SITES: TEKDEF
  MALSHARE_API_KEY: cb7364d8b6661a64066c3d40b3607c16ad26870b9b72f949e52169e96fb2775f
  VIRUSSHARE_API_KEY: 0iZGBKA0gICEO5RwTYKlFW7hxtSsLvaV
  storage_adapter_url2: http://storage-adapter-service:5002/
  storage_adapter_url: http://localhost:5002/
  MINIO_URL: play.min.io:80
  MINIO_ACCESS_KEY: Q3AM3UQ867SPQQA43P2F
  MINIO_SECRET_KEY: zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: glasswall-crawler
  labels:
    app: glasswall-crawler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: glasswall-crawler
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: glasswall-crawler
    spec:
      containers:
      - name: glasswall-crawler
        image: glasswallcrawler:1.0
        ports:
        - containerPort: 5002
        envFrom:
          - configMapRef:
              name: glasswall-crawler-configmap

        volumeMounts:
        - name: localtime-vol
          mountPath: /etc/localtime
        - name: timezone-vol
          mountPath: /etc/timezone

      volumes:
      - name: localtime-vol
        hostPath:
          path: /etc/localtime
      - name: timezone-vol
        hostPath:
          path: /etc/timezone
          type: File