
apiVersion: v1
kind: Service
metadata:
  labels:
    name: glasswall-rebuild
  name: glasswall-rebuild-service
spec:
  ports:
    - port: 5003
      targetPort: 5003
      protocol: TCP
  selector:
    app: glasswall-rebuild

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: glasswall-rebuild-configmap
data:
  PYTHONUNBUFFERED: 0

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: glasswall-rebuild
  labels:
    app: glasswall-rebuild
spec:
  replicas: 1
  selector:
    matchLabels:
      app: glasswall-rebuild
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: glasswall-rebuild
    spec:
      containers:
      - name: glasswall-rebuild
        image: glasswall-rebuild
        envFrom:
          - configMapRef:
              name: glasswall-rebuild-configmap
        ports:
        - containerPort: 5003

        volumeMounts:
        - name: localtime-vol
          mountPath: /etc/localtime
        - name: timezone-vol
          mountPath: /etc/timezone

      volumes:
      - name: localtime-vol
        hostPath:
          path: /etc/localtime
      - name: timezone-vol
        hostPath:
          path: /etc/timezone
          type: File