
apiVersion: v1
kind: Service
metadata:
  labels:
    name: storage-adapter
  name: storage-adapter-service
spec:
  ports:
    - port: 50051
      targetPort: 50051
      protocol: TCP
    - port: 5001
      targetPort: 5001
      protocol: TCP
  selector:
    app: storage-adapter

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: storage-adapter-configmap
data:
  auth_token: test_token
  PYTHONUNBUFFERED: 0
  MINIO_URL: http://minio-service:9000
  MINIO_ACCESS_KEY: minio1
  MINIO_SECRET_KEY: minio1@123

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-adapter
  labels:
    app: storage-adapter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storage-adapter
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: storage-adapter
    spec:
      containers:
      - name: storage-adapter
        image: k8-file-distribution
        envFrom:
          - configMapRef:
              name: storage-adapter-configmap

        volumeMounts:
        - name: localtime-vol
          mountPath: /etc/localtime
        - name: timezone-vol
          mountPath: /etc/timezone

      volumes:
      - name: localtime-vol
        hostPath:
          path: /etc/localtime
      - name: timezone-vol
        hostPath:
          path: /etc/timezone
          type: File