
apiVersion: v1
kind: Service
metadata:
  labels:
    name: k8-s3-sync
  name: k8-s3-sync-service
spec:
  ports:
    - port: 5004
      targetPort: 5004
      protocol: TCP
  selector:
    app: k8-s3-sync

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: k8-s3-sync-configmap
data:
  MINIO_URL: http://minio-service:9000
  MINIO_ACCESS_KEY: minio1
  MINIO_SECRET_KEY: minio1@123

  S3_ENDPOINT: https://s3.<S3_REGION>.amazonaws.com
  S3_ACCESS_KEY_ID: XXX
  S3_SECRET_ACCESS_KEY: XXX
  S3_REGION: XXX
  PYTHONUNBUFFERED: 0
  S3_BUCKET: XXX

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8-s3-sync
  labels:
    app: k8-s3-sync
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8-s3-sync
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: k8-s3-sync
    spec:
      containers:
      - name: k8-s3-sync
        image: k8-s3-sync
        envFrom:
          - configMapRef:
              name: k8-s3-sync-configmap
        ports:
        - containerPort: 5004

        volumeMounts:
        - name: localtime-vol
          mountPath: /etc/localtime
        - name: timezone-vol
          mountPath: /etc/timezone

      volumes:
      - name: localtime-vol
        hostPath:
          path: /etc/localtime
      - name: timezone-vol
        hostPath:
          path: /etc/timezone
          type: File