
apiVersion: v1
kind: Service
metadata:
  labels:
    name: rabbitmq-process
  name: rabbitmq-process-service
spec:
  ports:
    - port: 50057
      targetPort: 50057
      protocol: TCP
    - port: 5006
      targetPort: 5006
      protocol: TCP
  selector:
    app: rabbitmq-process

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-process-configmap
data:
  MINIO_ENDPOINT: minio-service:9000
  MINIO_ACCESS_KEY_ID: minio1
  MINIO_SECRET_ACCESS_KEY: minio1@123
  MINIO_SECURE: False
  MQ_USERNAME: guest
  MQ_PASSWORD: guest
  MQ_HOST: rabbitmq-service
  MQ_PORT: 5672
  MQ_EXCHANGE: 
  MQ_EXCHANGE_TYPE: 
  MQ_QUEUE: queue01
  MQ_ROUTING_KEY: queue01
  s3_sync_api: http://k8-s3-sync-service:5004/tos3
  file_processor_api: http://k8-file-processor-service:5000/process

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-process
  labels:
    app: rabbitmq-process
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq-process
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: rabbitmq-process
    spec:
      containers:
      - name: rabbitmq-process
        image: rabbit-mq:1.0
        envFrom:
          - configMapRef:
              name: rabbitmq-process-configmap

        volumeMounts:
        - name: localtime-vol
          mountPath: /etc/localtime
        - name: timezone-vol
          mountPath: /etc/timezone

      volumes:
      - name: localtime-vol
        hostPath:
          path: /etc/localtime
      - name: timezone-vol
        hostPath:
          path: /etc/timezone
          type: File