
apiVersion: v1
kind: Service
metadata:
  labels:
    name: rabbitmq
  name: rabbitmq-service
spec:
  ports:
    - port: 15672
      targetPort: 15672
      protocol: TCP
  selector:
    app: rabbitmq

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3-management
        ports:
        - containerPort: 15672
        readinessProbe:
          httpGet:
            path: /
            port: 15672
          initialDelaySeconds: 30
          periodSeconds: 20
        livenessProbe:
          httpGet:
            path: /
            port: 15672
          initialDelaySeconds: 30
          periodSeconds: 20

        volumeMounts:
        - name: localtime-vol
          mountPath: /etc/localtime
        - name: timezone-vol
          mountPath: /etc/timezone

      volumes:
      - name: localtime-vol
        hostPath:
          path: /etc/localtime
      - name: timezone-vol
        hostPath:
          path: /etc/timezone
          type: File